version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build

  run_tests:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  

workflows:
  build:
    jobs:
      - build
      - run_tests
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          no-output-timeout: 20m
          region: AWS_REGION
          repo: waffl-archive-react
          skip-when-tags-exist: false
          tag: 'latest'
      - aws-ecs/run-task:
          cluster: arn:aws:ec2:us-east-2:882165684475:instance/i-03e6be6b0d8c61975
          task-definition: deploy-react-image:1
