version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build

  run_tests:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test

workflows:
  build:
    jobs:
      - build
      - run_tests
