version: 2.1

# orbs:
#   node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build

workflows:
  build:
    jobs:
      - build
