version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build

  run_tests:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test

workflows:
  build:
    jobs:
      - build
      - run_tests
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          create-repo: true
          no-output-timeout: 20m
          region: AWS_REGION_ENV_VAR_NAME
          repo: WA2-Frontend
          skip-when-tags-exist: false
          tag: 'latest'
