version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build

  run_tests:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test

workflows:
  build:
    jobs:
      - build
      - run_tests
      - aws-ecr/build-and-push-image:
          account-url: 882165684475.dkr.ecr.us-east-2.amazonaws.com/waffl-archive-react
          region: us-east-2
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
