version: 2.1

# orbs:
#   node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build

  run_tests:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run:
        name: Install npm dependencies
        command: |
          sudo npm install -g
      - run:
        name: Run unit tests
        command: |
          npm run tests

workflows:
  build:
    jobs:
      - build
      - run_tests
